<?php

namespace Tests;

use PHPUnit\Framework\TestCase;

class AbstractTestCase extends TestCase
{
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
    
    
}
