<?php

namespace ArUtil\Tests;

use PHPUnit\Framework\TestCase;

class AbstractTestCase extends TestCase
{
    
    protected function setUp()
    {
        defined('TESTS_ROOT') ?: define('TESTS_ROOT', __DIR__);
        defined('LIBRARY_ROOT') ?: define('LIBRARY_ROOT', dirname(__DIR__));
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
    
    
}
