<?php

namespace Tests\Arabic;

use I18N_Arabic_Date;
use Tests\AbstractTestCase;

class DateTest extends AbstractTestCase
{
    
    /**
     * @var I18N_Arabic_Date
     */
    protected $date;
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->date = new \I18N_Arabic('Date');
    }
    
    /** @test */
    public function it_loads_date_class()
    {
        $this->assertInstanceOf(I18N_Arabic_Date::class, $this->date->myObject);
    }
}
