<?php

namespace Tests\Arabic;

use I18N_Arabic_Normalise;
use Tests\AbstractTestCase;

class NormaliseTest extends AbstractTestCase
{
    
    /**
     * @var I18N_Arabic_Normalise
     */
    protected $normalise;
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->normalise = new \I18N_Arabic('Normalise');
    }
    
    /** @test */
    public function it_loads_normalise_class()
    {
        $this->assertInstanceOf(I18N_Arabic_Normalise::class, $this->normalise->myObject);
    }
    
    /** @test */
    public function can_strip_tatweel()
    {
        $text = 'هـذا النــص يتحتــوي علــى تطويــــلات';
        $expected = 'هذا النص يتحتوي على تطويلات';
        $actualText = $this->normalise->stripTatweel($text);

        $this->assertEquals($expected, $actualText);
    }
    
    /** @test */
    public function can_strip_tashkeel()
    {
        $text = 'هَذَا النَّصُ يَحْتوي تشكيلاتٍ كُثرٍ';
        $expected = 'هذا النص يحتوي تشكيلات كثر';
        $actualText = $this->normalise->stripTashkeel($text);
    
        $this->assertEquals($expected, $actualText);
    }
    /** @test */
    public function can_normalise_hamza()
    {
        $text = 'إذا أنت أكرمت الكريم ملكته وإن أنت أكرمت اللئيم تمردا';
        $expected = 'اذا انت اكرمت الكريم ملكته وان انت اكرمت اللئيم تمردا';
        $actualText = $this->normalise->normaliseHamza($text);
    
        $this->assertEquals($expected, $actualText);
    }
    
    
}
