<?php

namespace Tests\Arabic;

use I18N_Arabic_Stemmer;
use Tests\AbstractTestCase;

class StemmerTest extends AbstractTestCase
{
    
    /**
     * @var \I18N_Arabic_Stemmer
     */
    protected $stemmer;
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stemmer = new \I18N_Arabic('Stemmer');
    }
    
    /** @test */
    public function it_loads_stemmer_class()
    {
        $this->assertInstanceOf(I18N_Arabic_Stemmer::class, $this->stemmer->myObject);
    }
    
    /** @test */
    public function it_return_a_rough_stem_of_the_given_Arabic_word()
    {
        $this->assertEquals('خيول', $this->stemmer->stem('الخيول'));
        $this->assertEquals('مختبر', $this->stemmer->stem('المختبرات'));
        $this->assertEquals('تطبيق', $this->stemmer->stem('التطبيقات'));
        $this->assertEquals('عامل', $this->stemmer->stem('العاملين'));
        $this->assertEquals('ذهب', $this->stemmer->stem('ذهبوا'));
//        $this->assertEquals('محكم', $this->stemmer->stem('المحكمين'));
    }
}
