<?php

namespace Tests\Arabic;

use I18N_Arabic_Stemmer;
use Tests\AbstractTestCase;

class StemmerTest extends AbstractTestCase
{
    
    /**
     * @var \I18N_Arabic_Stemmer
     */
    protected $stemmer;
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->stemmer = new \I18N_Arabic('Stemmer');
    }
    
    /** @test */
    public function it_loads_stemmer_class()
    {
        $this->assertInstanceOf(I18N_Arabic_Stemmer::class, $this->stemmer->myObject);
    }
}
